"""Replace all box/*.html left nav to match the updated box-template.html.

Previous scripts added spotlight/cluster sections to root articles but
the box pages were regenerated by generator.py losing these sections.
This rebuilds their left nav once so subsequent generator runs preserve it.

Idempotent: skips files that already have the cluster nav.
"""
from __future__ import annotations
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent

NEW_NAV = '''<a href="../box-toushi.html">BOX投資の始め方</a>
<a href="../restock-guide.html">再販情報の見つけ方</a>
<div class="article-nav-sub">🔥 BOX深掘り特集</div>
<a href="../151-spotlight.html">【特集】ポケモンカード151高騰</a>
<a href="../inferno-x-spotlight.html">【特集】インフェルノX高騰</a>
<a href="../kokuen-spotlight.html">【特集】黒炎の支配者高騰</a>
<div class="article-nav-sub" style="color:#6d28d9">📘 掘り下げガイド</div>
<a href="../zeppan-ranking-2026-03.html">📊 S&S以降 絶版BOXランキング</a>
<a href="../lizardon-box-guide.html">🔥 リザードン高騰BOX完全ガイド</a>
<a href="../mega-pack-compare.html">⚡ MEGA拡張パック完全比較</a>
<a href="../kokuen-vs-rocket.html">⚔️ 黒炎 vs ロケット団の栄光</a>
<a href="../mega-lizardon-x-guide.html">メガリザードンXex MUR/SAR</a>
<a href="../lizardon-sar-kokuen-guide.html">リザードンex SAR(黒炎)</a>
<a href="../erika-sar-guide.html">エリカの招待 SAR</a>
<a href="../pigeot-sar-guide.html">ピジョットex SAR</a>
<a href="../masterball-mirror-guide.html">151マスターボールミラー</a>
<a href="../kokuen-atari-guide.html">黒炎 当たりカード完全ガイド</a>
</nav>'''

# Marker: end of 一般記事 block in box pages (same as box-template pre-fix)
MARKER = '<a href="../box-toushi.html">BOX投資の始め方</a>\n</nav>'

SENTINEL = '📘 掘り下げガイド'


def process(path: Path) -> bool:
    content = path.read_text(encoding='utf-8')
    if SENTINEL in content:
        # Check if the SENTINEL is in the LEFT nav (not just mobile)
        # Left nav version has 'article-nav-sub' style="color:#6d28d9">📘
        if 'article-nav-sub" style="color:#6d28d9">📘' in content:
            return False  # already done
    if MARKER not in content:
        return False
    new = content.replace(MARKER, NEW_NAV, 1)
    path.write_text(new, encoding='utf-8')
    return True


def main():
    ok = 0
    for p in sorted((ROOT / "box").glob("*.html")):
        if process(p):
            ok += 1
            print(f"OK: box/{p.name}")
    print(f"\n=== {ok} files patched ===")


if __name__ == "__main__":
    main()
